import { Router } from "express";
import authRouter from "./auth.route";
import adminRouter from "./admin.route";
import userRouter from "./user.route";
import medicalRecordRouter from "./medical-record.route";
import vitalsRouter from "./vitals.route";
import symptomsRouter from "./symptoms.route";
import medicationsRouter from "./medications.route";
import medicalFileRouter from "./medical-file.route";
import userDataRouter from "./user-data.route";
import allergyRouter from "./allergy.route";
import immunizationRouter from "./immunization.route";
import notificationRouter from "./notification.route";
import aiScanRouter from "./ai-scan.route";
import aiInsightsRouter from "./ai-insights.route";
import aiChatRouter from "./ai-chat.route";
import fileProxyRouter from "./file-proxy.route";
import riskAssessmentRouter from "./risk-assessment.route";
import healthInsightsRouter from "./health-insights.route";
import analyticsRouter from "./analytics.route";
import dashboardRouter from "./dashboard.route";
import predictionRouter from "./prediction.route";
import familyGroupRouter from "./family-group.route";

const mainRouter = Router();

mainRouter.use("/auth", authRouter);
mainRouter.use("/admin", adminRouter);
mainRouter.use("/users", userRouter);
mainRouter.use("/medical-records", medicalRecordRouter);
mainRouter.use("/vitals", vitalsRouter);
mainRouter.use("/symptoms", symptomsRouter);
mainRouter.use("/medications", medicationsRouter);
mainRouter.use("/medical-files", medicalFileRouter);
mainRouter.use("/user-data", userDataRouter);
mainRouter.use("/allergies", allergyRouter);
mainRouter.use("/immunizations", immunizationRouter);
mainRouter.use("/notifications", notificationRouter);
mainRouter.use("/ai-scan", aiScanRouter);
mainRouter.use("/ai-insights", aiInsightsRouter);
mainRouter.use("/ai-chat", aiChatRouter);
mainRouter.use("/files", fileProxyRouter);
mainRouter.use("/risk-assessments", riskAssessmentRouter);
mainRouter.use("/health-insights", healthInsightsRouter);
mainRouter.use("/analytics", analyticsRouter);
mainRouter.use("/dashboard", dashboardRouter);
mainRouter.use("/predict", predictionRouter);
mainRouter.use("/family-groups", familyGroupRouter);

export default mainRouter;
